### ISSUE TITLE
Feature #1: User can enter a search term and view a list of results 

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/book-full-stack-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can navigate the homepage and enter search term  in the navbar. The book requested will be sent to the book API and it will respond with the list of books. The search results will be navigated to its own page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the perspective of the user, they will be able to navigate the homepage and click into the search bar and type in the name of a book. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-04-14 at 12 48 49 PM](https://user-images.githubusercontent.com/117954421/232141724-6b7e5ab3-ab5a-4a51-86d4-3d9801be688d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to ... render the entire homepage 
- [x] Create a component that will implement the search bar feature 
- [x] Create a component that will render the navbar with the search bar inside of it with the routing to wishlist and cart to be implemented later in development 
- [x] Create a component that will hard code pre selected books to be displayed on the home screen (will have to include information that can be accessed by the more info page" 
- [x] -Create a component that will display the About Us section 
- [x] - [ ] Configure React bootstrap to style the homepage
- [x] Create onClick for each image so that it will grab the isbn number and make a fetch request that will eventually render on the results page. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
