### ISSUE TITLE
Feature #2: User can view more details about a book

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/book-full-stack-project#2]
more-info-page
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can…view more details about the book clicked 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the perspective of the user, they can view more details about the book clicked. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-04-14 at 1 53 58 PM](https://user-images.githubusercontent.com/117954421/232152723-e427326b-5a66-4e76-a103-cd16eea51eaf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...
- [x] Create  a component that will render a More Info page when a photo is clicked 
- [x] Update the ResultsPage component to have an onClick that will show more info for the book being clicked 
- [x] Update the Homepage to have an onClick that will show more info for the book being clicked 
- [ ] 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
