### ISSUE TITLE
Feature #3: User can add a book to their cart 

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/book-full-stack-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a book to their cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the perspective of the user, they will be able to press the add to cart button and a visual confirmation will appear as a modal. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-04-14 at 2 05 57 PM](https://user-images.githubusercontent.com/117954421/232155022-fa898845-3974-4902-aafc-2b28d56f3b49.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] Update data.sql to add new books to be added to the cart when Add to Cart button is clicked on More Info Page.

### ☁️ Server Tasks

- [x] Update `server.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update 'server.js' to make a get request from the database 
- [x] Update 'server.js' to make a post request to the database 

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...
- [x] Create a file with a component that will render the CartList with items as its prop and map each 'item' appended to a UL
    - [x] Within that same file create a component that will take item as its prop 
- [x] In a separate file import the CartList that will be returned by the end of the this new component 
- [x] Create this new component with a useEffect that will fetch a GET request from our server and update a state with this new json response. should have an empty array dependency 
     - [x] Within this new component, create an async function that will take the parameter of newEntry and make a fetch response to the api with a post method
     - [x] Possibly will need to add an onSubmit prop to the MoreInfoPage so that when the button is clicked it will add this new entry. Will likely need to be imported as well 
- [x] Apply bootstrap to cart page 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
