### ISSUE TITLE
Feature #4: User can add a book to their wishlist  

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/book-full-stack-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a book to their wishlist 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the perspective of the user, they can click the add to wishlist button and a modal will appear confirming that it has been added 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-04-14 at 2 11 45 PM](https://user-images.githubusercontent.com/117954421/232155737-57bbe76b-ca0e-4686-b6e4-c3d7e021f620.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update server.js to make a get request from '/api/wishlist'
- [x] update server.js to make a get request from 'api/wishlist 

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...
- [x] Create a component WishListBook that will create the layout for each book that you want to add.  Make sure you give it a book, deleteBook from wishlist and addBook prop
     - [x] Add a new function to MoreInfoPage that will add to wishlist when clicked 
     - [x] make a WishList component that will map out each Book from WishListBook component 
 - [x] On a new file make a WishListPage component that will useEffect to make a GET request that will set the state to the jsonData the page with the wishlist fetch request once with a empty array dependency 
 - [x] Import addBook so that you can use it for your add to cart button 
 - [x] Apply bootstrap 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
