### ISSUE TITLE
Feature #6: User can delete a book from their cart  

### ISSUE THREAD

**Issue by devanrivera98** [devanrivera98/book-full-stack-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a book from their cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the perspective of the user, they can click on the X on the top right corner of each product and it will remove that item from the cart. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-04-14 at 2 15 48 PM](https://user-images.githubusercontent.com/117954421/232157598-71ea838f-1235-465a-a9cb-fdd99aa14014.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to ...
- [x] Test with HTTPie
- [x] Update server.js to allow a delete request to be made 
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the schema to add a quantity 
- [ ] 
- [x] Update CartList  for the component EachBook to take deleteBook as a prop 
- [x] In that same file you are going to want to update the CartList component to be passed a deleteBook prop and then give that prop when you map the books 
 -[ ] In the CheckoutPage you are going to want to create an async function that will be be making a fetch request to delete the cartId of the button being clicked  

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
